version: '3'
services:
  all:
    environment:
      - BUBNBROS_PORT=8000
    image: florianpiesche/bubnbros:${ARCH}-latest
    ports:
      - "8000:8000"
    container_name: bubnbros
    hostname: bubnbros
    build: .
